name: Web App Selenium Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        working-directory: ./web
        run: npm install

      - name: Build Web App
        working-directory: ./web
        run: npm run build

      - name: Start Web App Background
        working-directory: ./web
        run: npm run preview &
        
      - name: Wait for server
        run: sleep 5

      - name: Run Selenium Tests
        working-directory: ./web
        run: node test/run-selenium.js

      - name: Upload Excel Report
        uses: actions/upload-artifact@v3
        with:
          name: selenium-report
          path: ./reports/Selenium_Report.xlsx
